### ISSUE TITLE
openvino-inference-engine_2024.4.0.bb src branch was deleted

### ISSUE THREAD

**Issue by jwinarske** [intel/meta-openvino#12]
https://github.com/intel/meta-openvino/blob/main/recipes-core/opencv/openvino-inference-engine_2024.4.0.bb#L7

The branch doesn't exist anymore.

**Comment by yktyagi** [comment]
Hello @jwinarske ,

I tried the openvino-inference-engine build which fetches branch releases/2024/4 and it built without any issue.

**Comment by anujm1** [comment]
Please re-open or file a new bug if you still see a problem.

**Comment by jwinarske** [comment]
It works after this commit:  https://github.com/intel/meta-openvino/commit/7e308d183b06157d381cac9bf83fde5b9bfa6d65

Perhaps you forgot to push your change prior.
