### ISSUE TITLE
Failed to build openvino-inference-engine for qemuarm64 on master branch

### ISSUE THREAD

**Issue by yizhao1** [intel/meta-openvino#14]
When building openvino-inference-engine for qemuarm64, it hangs at the do_configure step. I used the default ycoto conf/local.conf and included the following layers in conf/bblayers.conf:
BBLAYERS ?= " \
  poky/meta \
  poky/meta-poky \
  poky/meta-yocto-bsp \
  poky/meta-openembedded/meta-oe \
  poky/meta-openembedded/meta-python \
  poky/meta-openvino \
  "

**Comment by anujm1** [comment]
I think `qemuarm64` might still not work because of the instructions required by `mlas` but this PR might help with the other problem: https://github.com/intel/meta-openvino/pull/16

**Comment by yizhao1** [comment]
So can we temporarily add COMPATIBLE_HOST back to openvino-inference-engine and open-model-zoo recipes?

**Comment by anujm1** [comment]
> So can we temporarily add COMPATIBLE_HOST back to openvino-inference-engine and open-model-zoo recipes?

I didn't understand. Is there an expectation that `qemuarm64` should be able to build these recipes?

**Comment by yizhao1** [comment]
I have sent a patch #17 to set COMPATIBLE_HOST for x86_64

**Comment by anujm1** [comment]
This isn't expected to work with `qemuarm64` as it is today because of limitations placed by `mlas`. If this is needed, please help by making the changes that will be required.
