### ISSUE TITLE
arm-compute-library: Build failures with scarthgap due to UNPACKDIR

### ISSUE THREAD

**Issue by cshilwant** [intel/meta-openvino#15]
With commit https://github.com/intel/meta-openvino/commit/3a7edf05f33d62046cd3e8c4154753ba0d5c115a, the arm-compute-library recipe will no longer build cleanly on scarthgap (do_install fails) even though the layer.conf still recommends scarthgap with LAYERSERIES_COMPAT - https://github.com/intel/meta-openvino/commit/5b8be72c0ef0f234446f4a7f7e370cf20486c8db

Are there any plans to branchout scarthgap and continue with main being styhead?

**Comment by yktyagi** [comment]
scarthgap branch has been pushed to meta-openvino repo. Please use scarthgap branch.
